const PHONE='94779507683';
const products=[
{name:'6x4 Cupboard – Mirror',price:'Rs. 34,000/=',image:'images/cupboard-1.jpg',description:'Premium Melamine cupboard with full-length mirror and spacious storage.',features:['Full-length mirror','Multiple storage areas','Melamine finish'],warranty:'3 Year Warranty'},
{name:'6x4 Cupboard – Plain',price:'Rs. 32,000/=',image:'images/cupboard-5.jpg',description:'Spacious Melamine cupboard with multiple shelves and hanging space.',features:['Shelves','Hanging space','Neat Melamine finish'],warranty:''},
{name:'Sliding Door Cupboard',price:'Rs. 38,000/=',image:'images/cupboard-2.jpg',description:'Space-saving sliding-door Melamine cupboard with modern finishing.',features:['Sliding doors','Space-saving design','Modern finish'],warranty:''},
{name:'3 Door Wardrobe',price:'Rs. 42,000/=',image:'images/cupboard-4.jpg',description:'Modern three-door wardrobe with practical storage compartments.',features:['Three doors','Practical compartments','Melamine finish'],warranty:''},
{name:'Custom Made Cupboard',price:'Ask for Price',image:'images/cupboard-6.jpg',description:'Custom furniture designed according to your preferred size, color and storage requirements.',features:['Custom size','Custom color','Custom storage layout'],warranty:''},
{name:'Bedroom Furniture Set',price:'Contact Us',image:'images/cupboard-3.jpg',description:'Matching Melamine bedroom furniture designed for a clean and stylish bedroom.',features:['Matching pieces','Bedroom-focused storage','Modern look'],warranty:''}
];
const wa=(message)=>`https://wa.me/${PHONE}?text=${encodeURIComponent(message)}`;
const menu=document.querySelector('.menu-toggle'), nav=document.querySelector('.nav-links');
menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});
document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const filters=[...document.querySelectorAll('[data-filter]')];
function setFilter(value){document.querySelectorAll('.product-card').forEach(card=>{card.classList.toggle('hide',value!=='all'&&card.dataset.category!==value)});document.querySelectorAll('.filter,.cat').forEach(b=>b.classList.toggle('active',b.dataset.filter===value))}
filters.forEach(b=>b.addEventListener('click',()=>{const value=b.dataset.filter;setFilter(value);if(b.classList.contains('cat'))document.querySelector('#products').scrollIntoView({behavior:'smooth'})}));
const modal=document.getElementById('productModal'), modalContent=document.getElementById('modalContent');
document.querySelectorAll('.product-card').forEach(card=>card.addEventListener('click',e=>{if(!e.target.classList.contains('product-btn')&&!card.contains(e.target))return;const p=products[Number(card.dataset.id)];modalContent.innerHTML=`<div class="modal-product"><img src="${p.image}" alt="${p.name}"><div><span class="section-kicker">ALOKA FURNITURE</span><h2>${p.name}</h2><p>${p.description}</p><div class="modal-price">${p.price}</div><h4>Features</h4><ul>${p.features.map(x=>`<li>${x}</li>`).join('')}</ul>${p.warranty?`<p><b>${p.warranty}</b></p>`:''}<a class="btn yellow" href="${wa(`Hello Aloka Furniture, I am interested in ${p.name}. Please send me more details.`)}" target="_blank" rel="noopener">WhatsApp Inquiry →</a></div></div>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}));
const gallery=[...document.querySelectorAll('.gallery-item img')].map(i=>i.src);let current=0;const light=document.getElementById('lightbox'), lightImage=document.getElementById('lightImage');function showLight(i){current=(i+gallery.length)%gallery.length;lightImage.src=gallery[current];lightImage.alt=`Aloka Furniture gallery image ${current+1}`;light.classList.add('open');light.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}document.querySelectorAll('.gallery-item').forEach(b=>b.addEventListener('click',()=>showLight(Number(b.dataset.index))));document.getElementById('lightPrev').onclick=()=>showLight(current-1);document.getElementById('lightNext').onclick=()=>showLight(current+1);
function close(id){const el=document.getElementById(id);el.classList.remove('open');el.setAttribute('aria-hidden','true');document.body.style.overflow=''}document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>close(b.dataset.close)));document.addEventListener('keydown',e=>{if(e.key==='Escape'){close('productModal');close('lightbox')}if(light.classList.contains('open')){if(e.key==='ArrowLeft')showLight(current-1);if(e.key==='ArrowRight')showLight(current+1)}});
const form=document.getElementById('contactForm'), success=document.getElementById('formSuccess');form.addEventListener('submit',e=>{e.preventDefault();success.className='form-success';if(!form.name.value.trim()||!form.phone.value.trim()||!form.message.value.trim()){success.className='form-error';success.textContent='Please complete your name, phone number and message.';return}success.textContent='Thank you! Your inquiry has been received. We will contact you soon.';form.reset()});
const back=document.getElementById('backTop');window.addEventListener('scroll',()=>{back.classList.toggle('show',scrollY>500);const sections=[...document.querySelectorAll('main section[id]')];let currentId='home';sections.forEach(s=>{if(scrollY>=s.offsetTop-130)currentId=s.id});document.querySelectorAll('.nav-links>a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${currentId}`))},{passive:true});back.onclick=()=>scrollTo({top:0,behavior:'smooth'});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
